### PR TITLE
Use the latest version of mongo that will work on older systems, see …

### PR DESCRIPTION
**Pull request by PaulGWebster**
… https://github.com/petio-team/petio/issues/533

### CODE REVIEW

**Review by oalders — APPROVED** [review]
This seems fine to me. `github-meets-cpan` hasn't been touched in a long time. I don't know of a reason that it would need the latest `MongoDB`.

**Comment by ssoriche** [comment]
My view would be the opposite, what is it that's stopping mongo from running at the latest, can we upgrade that?

My assumption here is that the "older system" is the OS in the base docker image, and if that's the case, the right solution is to update the OS to the latest release.

**Comment by oalders** [comment]
https://github.com/metacpan/metacpan-base/blob/main/Dockerfile#L2

```
ARG PERL_VERSION=5.30
FROM perl:${PERL_VERSION} AS build
```

**Comment by ssoriche** [comment]
Are you saying we're blocked by the `perl` image? I've long wanted to build our own perl images. Perhaps the right solution here is to approve this merge request for now, and replace the base image with our own built perl image separately.

**Comment by oalders** [comment]
I don't know if we're blocked. There are various official `Perl` images to choose from if we wanted to go that route. I'm fine with building our own Perl as well.

Having said that, merging this would fix the immediate problem. Nobody has hacked on that repo for years, so I think it's fine to freeze the `MongoDB` version and build a new base version on our own timeline.

**Review by ssoriche — APPROVED** [review]
LGTM

**Comment by PaulGWebster** [comment]
> I don't know if we're blocked. There are various official `Perl` images to choose from if we wanted to go that route. I'm fine with building our own Perl as well.
> 
> Having said that, merging this would fix the immediate problem. Nobody has hacked on that repo for years, so I think it's fine to freeze the `MongoDB` version and build a new base version on our own timeline.

I would not mind helping out with that, if my help was wanted - building perl images that is (I actually have a task like this lined up for work!)

**Comment by PaulGWebster** [comment]
> My view would be the opposite, what is it that's stopping mongo from running at the latest, can we upgrade that?
> 
> My assumption here is that the "older system" is the OS in the base docker image, and if that's the case, the right solution is to update the OS to the latest release.

Also there is an issue with monodb running on older hardware, something about an AVX instruction set

**Pull request merged**
