### PR TITLE
web now exposes port 80 rather than 5001

### PR DESCRIPTION
**Pull request by oalders**

### CODE REVIEW

**Review by mickeyn — APPROVED** [review]

**Comment by LeoLapworthKT** [comment]
Why port 80?

Won't that mean escalated privileges are needed?

**Comment by haarg** [comment]
It's using port 80 inside the container, where it has the privileges necessary. This still uses port 5001 externally, so it doesn't need any special privileges outside the container.

**Comment by ranguard** [comment]
> It's using port 80 inside the container, where it has the privileges necessary. This still uses port 5001 externally, so it doesn't need any special privileges outside the container.

Ahh, I always get those the wrong way around... 

So this won't have any affect on https://github.com/metacpan/metacpan-k8s/blob/main/apps/web/base/deployment.yaml#L36 ?

**Comment by haarg** [comment]
This repo is only for the development setup and isn't used by production for anything.

The default port used inside the container was already changed to 80, so this is just updating the compose setup to point to it.

The k8s setup is overriding the port used internally, so it is free to use whatever it wants.

**Pull request merged**
