### PR TITLE
Run the MetaCPAN in Docker Compose

### LINKED ISSUE #10: Fix building this project and make it robust
The current version of metacpan-docker is completly broken. It worked fine when it was createad (about a year ago), but now it does not work. The problem is that the surrounding world has changed. Some packages disappeared (see #9 ), some new dependencies appeared ( see #6 )

This project has to be fixed. The main idea that we need to create this project in the way the changes in the surrounding world should not matter. We need to explicitly specify all the dependencies and versions.

The other thing that I want to be done is to simplify the process of running this project.

So, this is the plan:
- use docker-compose
- remove elasticsearch Dockerfile and to use elasticsearch image from the docker hub
- explicitly specify git commits from cpan-api and metacpan-web project

I'm going to implement it in the separate git branch `dev`

### PR DESCRIPTION
**Pull request by zakame**
This is an overhaul of the metacpan-docker configuration described here, now using Docker Compose.  This means that it setting up MetaCPAN in Docker should be as simple as

    git clone https://github.com/metacpan/metacpan-docker.git
    cd metacpan-docker
    bin/metacpan-docker init
    bin/metacpan-docker localapi up
    # ... and in another terminal
    bin/metacpan-docker localapi run --rm api index-cpan.sh

Not quite as simple as 1, 2, 3, but hopefully getting there :)

Kindly refer to the updated `README.md` for the details.

Possibly fixes #10, #9, #8, and #7.

### CODE REVIEW

**Comment by zakame** [comment]
This depends on https://github.com/metacpan/metacpan-api/pull/704 and https://github.com/metacpan/metacpan-web/pull/1935 for the corresponding Docker images to be built.

**Comment by oalders** [comment]
@bessarabov are you able to review the web and api pull requests that this depends on as well?

**Comment by zakame** [comment]
Hi, any movement for review?

**Comment by oalders** [comment]
Is @bessarabov the right person to review this or is there someone else who should do it?

**Comment by zakame** [comment]
Thanks, I suppose someone else can review, though I think this PR might need updating.

**Comment by oalders** [comment]
@zakame could you check to see if the PR needs updating?  Once that's done could you comment on the PR?  I'll chase someone down for a review.

**Comment by oalders** [comment]
Thanks @zakame!  Any and all help is appreciated.  With PTS going on, we're highly available to review code.  :)

**Comment by zakame** [comment]
Thanks @oalders ! :tada:

**Pull request merged**
